### ISSUE TITLE
REPORTE LIBRERIA DLL

### ISSUE THREAD

**Issue by IMA-G** [SistemasTecTlaxiaco/practica-en-dll-en-c-en-visual-studio-IMA-G#2]
[LIBRERIA DLL.pdf](https://github.com/SistemasTecTlaxiaco/practica-en-dll-en-c-en-visual-studio-IMA-G/files/6353614/LIBRERIA.DLL.pdf)

**Comment by MariaC232** [comment]
Calificación: 20

**Comment by josealfredo79** [comment]
Bien hecho y revisado.
